#page title
page_title: No Varal # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 1669100114 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country: BR # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

app_icon: assets/appicon.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: No Varal # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Split the bill with your friends quickly and easily.

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Hugo Branco
your_link: https://hugobrancowb.github.io/
your_city: Brazil
email_address: hugobrancowb@gmail.com
facebook_username:
instagram_username:
github_username: hugobrancowb
youtube_username: hugobranco

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Quick and easy
    description: Easily split expenses between friends and family
    fontawesome_icon_name: magic

  - title: Simple steps
    description: Simply add the name of each person splitting and assign the items consumed to each one of them.
    fontawesome_icon_name: clock

  - title: Never do math at table again
    description: No Varal will automatically calculate each person's share and ease the process of payment.
    fontawesome_icon_name: calculator

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.3
topbar_title_color: "#ffffff"

cover_image: # assets/headerimage.png                  # Replace with alternative image path or image URL.
cover_overlay_color: "#FFB5A0"
cover_overlay_transparency: 1

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#652C1B"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#ffffff"
feature_icons_background_color: "#652C1B"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#ffffff"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
